dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

tests:
  Haskell-test:
    main:                OderedSpec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Haskell
    - hspec
